package com.nextsolutions.keyysafe.common.util

object ArgumentKeys {
    const val ENTRY_ID_TO_EDIT_CREATE_ENTRY_SCREEN_KEY = "ENTRY_ID_TO_EDIT_CREATE_ENTRY_SCREEN_KEY"
    const val LABEL_ID_TO_VIEW_ALL_ENTRIES_SCREEN = "LABEL_ID_TO_VIEW_ALL_ENTRIES_SCREEN"
    const val LABEL_ID_TO_VIEW_ENTRIES_BY_STRENGTH_SCREEN = "LABEL_ID_TO_VIEW_ENTRIES_BY_STRENGTH_SCREEN"
    const val PASSWORD_STRENGTH_TO_VIEW_ENTRIES_BY_PASSWORD_STRENGTH = "PASSWORD_STRENGTH_TO_VIEW_ENTRIES_BY_PASSWORD_STRENGTH"
    const val AUTH_SCREEN_USABILITY = "AUTH_SCREEN_USABILITY"
    const val AUTH_SCREEN_CONFIRM_AUTH_RESULT_KEY = "AUTH_SCREEN_CONFIRM_AUTH_RESULT_KEY"
    const val PASS_GENERATED_PASSWORD_BACK = "PASS_GENERATED_PASSWORD_BACK"
    const val SHOULD_PASS_GENERATED_PASSWORD_BACK = "SHOULD_PASS_GENERATED_PASSWORD_BACK"
    const val FILE_URI_TO_VIEW_FILE_DATA = "FILE_URI_TO_VIEW_FILE_DATA"
}